#!/bin/bash
# Event handler for VPN failure

case "$1" in
OK)
        ;;
WARNING)
        ;;
UNKNOWN)
        ;;
CRITICAL)
        case "$2" in
        SOFT)
                case "$3" in
                3)
                        ;;
                        esac
                ;;

        HARD)
                echo -n "shits fucked bruv"
                transmission-remote 192.168.1.101:9091 --auth user:password -t all --stop
                ;;
        esac
        ;;
esac
exit 0
